### PR TITLE
fix(core):feature-modules

### PR DESCRIPTION
**Pull request by deebloo**
This should fix issues based on requiring a parent state stream for a feature module.
Now what happens is the state stream is injected and IF there is a parent it uses that stream.

### CODE REVIEW

**Comment by deebloo** [comment]
@amcdnl before we merge this in could you give it a try in your project?

**Comment by yarrgh** [comment]
👍 Works as far as I can tell (for both lazy and non lazy loaded modules)

**Comment by leon** [comment]
@deebloo Why did you remove ChromeHeadless?

**Comment by deebloo** [comment]
@leon it isn't needed for circle

**Comment by amcdnl** [comment]
Works! :)

**Pull request merged**
